### ISSUE TITLE
Using this class as foundation for R package 

### ISSUE THREAD

**Issue by tbradley1013** [DrexelPhysics/drexel-thesis#6]
I would like to use this class to create an R package that allows for users to easily integrate the Drexel thesis requirements into a R bookdown project so that they can write their thesis in Rmarkdown rather than in pure LaTeX. 

This has been done for several other universities with the original being [here](https://github.com/ismayc/thesisdown). As far as I can tell, the majority of what I will have to do is just generate the `.cls` document class file from this repo and then insert into the format provided by the linked repo. 

I have already started working on this, but wanted to make sure that you were ok with my adaptation of your work before I got to much further. The  `.cls` will retain all of the copyright information automatically generated and I will also credit you in the template.tex comments. 

You can see the progress of this [here](https://github.com/tbradley1013/dragondown) if you are interested.

**Comment by thoppe** [comment]
That sounds great! Please note that this `.cls` file was created for members of the physics department and may be a bit more specific to our requirements there. I'll let the others members weigh in, but we don't visit this repo too often (we graduated :smile:). 

If you don't hear from anyone else in a week, assume it's good to go!
